/** biome-ignore-all lint/style/useConsistentArrayType: <explanation> */
/** biome-ignore-all lint/nursery/useConsistentTypeDefinitions: <explanation> */

type CallSettings = {
  /**
  Maximum number of tokens to generate.
     */
  maxOutputTokens?: number;
  /**
  Temperature setting. The range depends on the provider and model.
  
  It is recommended to set either `temperature` or `topP`, but not both.
     */
  temperature?: number;
  /**
  Nucleus sampling. This is a number between 0 and 1.
  
  E.g. 0.1 would mean that only tokens with the top 10% probability mass
  are considered.
  
  It is recommended to set either `temperature` or `topP`, but not both.
     */
  topP?: number;
  /**
  Only sample from the top K options for each subsequent token.
  
  Used to remove "long tail" low probability responses.
  Recommended for advanced use cases only. You usually only need to use temperature.
     */
  topK?: number;
  /**
  Presence penalty setting. It affects the likelihood of the model to
  repeat information that is already in the prompt.
  
  The presence penalty is a number between -1 (increase repetition)
  and 1 (maximum penalty, decrease repetition). 0 means no penalty.
     */
  presencePenalty?: number;
  /**
  Frequency penalty setting. It affects the likelihood of the model
  to repeatedly use the same words or phrases.
  
  The frequency penalty is a number between -1 (increase repetition)
  and 1 (maximum penalty, decrease repetition). 0 means no penalty.
     */
  frequencyPenalty?: number;
  /**
  Stop sequences.
  If set, the model will stop generating text when one of the stop sequences is generated.
  Providers may have limits on the number of stop sequences.
     */
  stopSequences?: string[];
  /**
  The seed (integer) to use for random sampling. If set and supported
  by the model, calls will generate deterministic results.
     */
  seed?: number;
  /**
  Maximum number of retries. Set to 0 to disable retries.
  
  @default 2
     */
  maxRetries?: number;
  /**
  Abort signal.
     */
  abortSignal?: AbortSignal;
  /**
  Additional HTTP headers to be sent with the request.
  Only applicable for HTTP-based providers.
     */
  headers?: Record<string, string | undefined>;
};

interface StreamTextResult<TOOLS extends ToolSet, PARTIAL_OUTPUT> {
  /**
  The content that was generated in the last step.
  
  Automatically consumes the stream.
     */
  readonly content: Promise<Array<ContentPart<TOOLS>>>;
  /**
  The full text that has been generated by the last step.
  
  Automatically consumes the stream.
       */
  readonly text: Promise<string>;
  /**
  The full reasoning that the model has generated.
  
  Automatically consumes the stream.
     */
  readonly reasoning: Promise<Array<ReasoningPart>>;
  /**
  The reasoning that has been generated by the last step.
  
  Automatically consumes the stream.
       */
  readonly reasoningText: Promise<string | undefined>;
  /**
  Files that have been generated by the model in the last step.
  
  Automatically consumes the stream.
     */
  readonly files: Promise<GeneratedFile[]>;
  /**
  Sources that have been used as references in the last step.
  
  Automatically consumes the stream.
     */
  readonly sources: Promise<Source[]>;
  /**
  The tool calls that have been executed in the last step.
  
  Automatically consumes the stream.
       */
  readonly toolCalls: Promise<TypedToolCall<TOOLS>[]>;
  /**
  The static tool calls that have been executed in the last step.
  
  Automatically consumes the stream.
       */
  readonly staticToolCalls: Promise<StaticToolCall<TOOLS>[]>;
  /**
  The dynamic tool calls that have been executed in the last step.
  
  Automatically consumes the stream.
       */
  readonly dynamicToolCalls: Promise<DynamicToolCall[]>;
  /**
  The static tool results that have been generated in the last step.
  
  Automatically consumes the stream.
       */
  readonly staticToolResults: Promise<StaticToolResult<TOOLS>[]>;
  /**
  The dynamic tool results that have been generated in the last step.
  
  Automatically consumes the stream.
       */
  readonly dynamicToolResults: Promise<DynamicToolResult[]>;
  /**
  The tool results that have been generated in the last step.
  
  Automatically consumes the stream.
     */
  readonly toolResults: Promise<TypedToolResult<TOOLS>[]>;
  /**
  The reason why the generation finished. Taken from the last step.
  
  Automatically consumes the stream.
       */
  readonly finishReason: Promise<FinishReason>;
  /**
  The token usage of the last step.
  
  Automatically consumes the stream.
     */
  readonly usage: Promise<LanguageModelUsage>;
  /**
  The total token usage of the generated response.
  When there are multiple steps, the usage is the sum of all step usages.
  
  Automatically consumes the stream.
       */
  readonly totalUsage: Promise<LanguageModelUsage>;
  /**
  Warnings from the model provider (e.g. unsupported settings) for the first step.
  
  Automatically consumes the stream.
       */
  readonly warnings: Promise<CallWarning[] | undefined>;
  /**
  Details for all steps.
  You can use this to get information about intermediate steps,
  such as the tool calls or the response headers.
  
  Automatically consumes the stream.
     */
  readonly steps: Promise<Array<StepResult<TOOLS>>>;
  /**
  Additional request information from the last step.
  
  Automatically consumes the stream.
   */
  readonly request: Promise<LanguageModelRequestMetadata>;
  /**
  Additional response information from the last step.
  
  Automatically consumes the stream.
   */
  readonly response: Promise<
    LanguageModelResponseMetadata & {
      /**
  The response messages that were generated during the call. It consists of an assistant message,
  potentially containing tool calls.
  
  When there are tool results, there is an additional tool message with the tool results that are available.
  If there are tools that do not have execute functions, they are not included in the tool results and
  need to be added separately.
         */
      messages: Array<ResponseMessage>;
    }
  >;
  /**
  Additional provider-specific metadata from the last step.
  Metadata is passed through from the provider to the AI SDK and
  enables provider-specific results that can be fully encapsulated in the provider.
     */
  readonly providerMetadata: Promise<ProviderMetadata | undefined>;
  /**
    A text stream that returns only the generated text deltas. You can use it
    as either an AsyncIterable or a ReadableStream. When an error occurs, the
    stream will throw the error.
       */
  readonly textStream: AsyncIterableStream<string>;
  /**
    A stream with all events, including text deltas, tool calls, tool results, and
    errors.
    You can use it as either an AsyncIterable or a ReadableStream.
    Only errors that stop the stream, such as network errors, are thrown.
       */
  readonly fullStream: AsyncIterableStream<TextStreamPart<TOOLS>>;
  /**
  A stream of partial outputs. It uses the `experimental_output` specification.
     */
  readonly experimental_partialOutputStream: AsyncIterableStream<PARTIAL_OUTPUT>;
  /**
  Consumes the stream without processing the parts.
  This is useful to force the stream to finish.
  It effectively removes the backpressure and allows the stream to finish,
  triggering the `onFinish` callback and the promise resolution.
  
  If an error occurs, it is passed to the optional `onError` callback.
    */
  consumeStream(options?: ConsumeStreamOptions): Promise<void>;
  /**
    Converts the result to a UI message stream.
  
    @param options.getErrorMessage an optional function that converts an error to an error message.
    @param options.sendUsage whether to send the usage information to the client. Defaults to true.
    @param options.sendReasoning whether to send the reasoning information to the client. Defaults to false.
    @param options.sendSources whether to send the sources information to the client. Defaults to false.
    @param options.experimental_sendFinish whether to send the finish information to the client. Defaults to true.
    @param options.experimental_sendStart whether to send the start information to the client. Defaults to true.
  
    @return A UI message stream.
       */
  toUIMessageStream<UI_MESSAGE extends UIMessage>(
    options?: UIMessageStreamOptions<UI_MESSAGE>
  ): AsyncIterableStream<InferUIMessageChunk<UI_MESSAGE>>;
  /**
    Writes UI message stream output to a Node.js response-like object.
    @param response A Node.js response-like object (ServerResponse).
    @param options.status The status code.
    @param options.statusText The status text.
    @param options.headers The headers.
    @param options.getErrorMessage An optional function that converts an error to an error message.
    @param options.sendUsage Whether to send the usage information to the client. Defaults to true.
    @param options.sendReasoning Whether to send the reasoning information to the client. Defaults to false.
       */
  pipeUIMessageStreamToResponse<UI_MESSAGE extends UIMessage>(
    response: ServerResponse,
    options?: UIMessageStreamResponseInit & UIMessageStreamOptions<UI_MESSAGE>
  ): void;
  /**
    Writes text delta output to a Node.js response-like object.
    It sets a `Content-Type` header to `text/plain; charset=utf-8` and
    writes each text delta as a separate chunk.
    @param response A Node.js response-like object (ServerResponse).
    @param init Optional headers, status code, and status text.
       */
  pipeTextStreamToResponse(response: ServerResponse, init?: ResponseInit): void;
  /**
    Converts the result to a streamed response object with a stream data part stream.
  
    @param options.status The status code.
    @param options.statusText The status text.
    @param options.headers The headers.
    @param options.getErrorMessage An optional function that converts an error to an error message.
    @param options.sendUsage Whether to send the usage information to the client. Defaults to true.
    @param options.sendReasoning Whether to send the reasoning information to the client. Defaults to false.
    @return A response object.
       */
  toUIMessageStreamResponse<UI_MESSAGE extends UIMessage>(
    options?: UIMessageStreamResponseInit & UIMessageStreamOptions<UI_MESSAGE>
  ): Response;
  /**
    Creates a simple text stream response.
    Each text delta is encoded as UTF-8 and sent as a separate chunk.
    Non-text-delta events are ignored.
    @param init Optional headers, status code, and status text.
       */
  toTextStreamResponse(init?: ResponseInit): Response;
}

export function streamText<
  TOOLS extends ToolSet,
  OUTPUT = never,
  PARTIAL_OUTPUT = never,
>({
  model,
  tools,
  toolChoice,
  system,
  prompt,
  messages,
  maxRetries,
  abortSignal,
  headers,
  stopWhen,
  experimental_output: output,
  experimental_telemetry: telemetry,
  prepareStep,
  providerOptions,
  experimental_activeTools,
  activeTools,
  experimental_repairToolCall: repairToolCall,
  experimental_transform: transform,
  includeRawChunks,
  onChunk,
  onError,
  onFinish,
  onAbort,
  onStepFinish,
  experimental_context,
  _internal: { now, generateId, currentDate },
  ...settings
}: CallSettings &
  Prompt & {
    /**
The language model to use.
     */
    model: LanguageModel;
    /**
The tools that the model can call. The model needs to support calling tools.
    */
    tools?: TOOLS;
    /**
The tool choice strategy. Default: 'auto'.
     */
    toolChoice?: ToolChoice<TOOLS>;
    /**
Condition for stopping the generation when there are tool results in the last step.
When the condition is an array, any of the conditions can be met to stop the generation.

@default stepCountIs(1)
     */
    stopWhen?:
      | StopCondition<NoInfer<TOOLS>>
      | Array<StopCondition<NoInfer<TOOLS>>>;
    /**
Optional telemetry configuration (experimental).
     */
    experimental_telemetry?: TelemetrySettings;
    /**
Additional provider-specific options. They are passed through
to the provider from the AI SDK and enable provider-specific
functionality that can be fully encapsulated in the provider.
 */
    providerOptions?: ProviderOptions;
    /**
     * @deprecated Use `activeTools` instead.
     */
    experimental_activeTools?: Array<keyof NoInfer<TOOLS>>;
    /**
   Limits the tools that are available for the model to call without
   changing the tool call and result types in the result.
        */
    activeTools?: Array<keyof NoInfer<TOOLS>>;
    /**
Optional specification for parsing structured outputs from the LLM response.
     */
    experimental_output?: Output<OUTPUT, PARTIAL_OUTPUT>;
    /**
Optional function that you can use to provide different settings for a step.

@param options - The options for the step.
@param options.steps - The steps that have been executed so far.
@param options.stepNumber - The number of the step that is being executed.
@param options.model - The model that is being used.

@returns An object that contains the settings for the step.
If you return undefined (or for undefined settings), the settings from the outer level will be used.
    */
    prepareStep?: PrepareStepFunction<NoInfer<TOOLS>>;
    /**
A function that attempts to repair a tool call that failed to parse.
     */
    experimental_repairToolCall?: ToolCallRepairFunction<TOOLS>;
    /**
Optional stream transformations.
They are applied in the order they are provided.
The stream transformations must maintain the stream structure for streamText to work correctly.
     */
    experimental_transform?:
      | StreamTextTransform<TOOLS>
      | Array<StreamTextTransform<TOOLS>>;
    /**
Whether to include raw chunks from the provider in the stream.
When enabled, you will receive raw chunks with type 'raw' that contain the unprocessed data from the provider.
This allows access to cutting-edge provider features not yet wrapped by the AI SDK.
Defaults to false.
     */
    includeRawChunks?: boolean;
    /**
Callback that is called for each chunk of the stream.
The stream processing will pause until the callback promise is resolved.
     */
    onChunk?: StreamTextOnChunkCallback<TOOLS>;
    /**
Callback that is invoked when an error occurs during streaming.
You can use it to log errors.
The stream processing will pause until the callback promise is resolved.
     */
    onError?: StreamTextOnErrorCallback;
    /**
Callback that is called when the LLM response and all request tool executions
(for tools that have an `execute` function) are finished.

The usage is the combined usage of all steps.
     */
    onFinish?: StreamTextOnFinishCallback<TOOLS>;
    onAbort?: StreamTextOnAbortCallback<TOOLS>;
    /**
Callback that is called when each step (LLM call) is finished, including intermediate steps.
    */
    onStepFinish?: StreamTextOnStepFinishCallback<TOOLS>;
    /**
     * Context that is passed into tool execution.
     *
     * Experimental (can break in patch releases).
     *
     * @default undefined
     */
    experimental_context?: unknown;
    /**
Internal. For test use only. May change without notice.
     */
    _internal?: {
      now?: () => number;
      generateId?: IdGenerator;
      currentDate?: () => Date;
    };
  }): StreamTextResult<TOOLS, PARTIAL_OUTPUT>;

interface GenerateTextResult<TOOLS extends ToolSet, OUTPUT> {
  /**
  The content that was generated in the last step.
     */
  readonly content: Array<ContentPart<TOOLS>>;
  /**
  The text that was generated in the last step.
       */
  readonly text: string;
  /**
  The full reasoning that the model has generated in the last step.
     */
  readonly reasoning: Array<ReasoningPart>;
  /**
  The reasoning text that the model has generated in the last step. Can be undefined if the model
  has only generated text.
     */
  readonly reasoningText: string | undefined;
  /**
  The files that were generated in the last step.
  Empty array if no files were generated.
       */
  readonly files: Array<GeneratedFile>;
  /**
  Sources that have been used as references in the last step.
     */
  readonly sources: Array<Source>;
  /**
  The tool calls that were made in the last step.
     */
  readonly toolCalls: Array<TypedToolCall<TOOLS>>;
  /**
  The static tool calls that were made in the last step.
     */
  readonly staticToolCalls: Array<StaticToolCall<TOOLS>>;
  /**
  The dynamic tool calls that were made in the last step.
     */
  readonly dynamicToolCalls: Array<DynamicToolCall>;
  /**
  The results of the tool calls from the last step.
     */
  readonly toolResults: Array<TypedToolResult<TOOLS>>;
  /**
  The static tool results that were made in the last step.
     */
  readonly staticToolResults: Array<StaticToolResult<TOOLS>>;
  /**
  The dynamic tool results that were made in the last step.
     */
  readonly dynamicToolResults: Array<DynamicToolResult>;
  /**
  The reason why the generation finished.
     */
  readonly finishReason: FinishReason;
  /**
  The token usage of the last step.
     */
  readonly usage: LanguageModelUsage;
  /**
  The total token usage of all steps.
  When there are multiple steps, the usage is the sum of all step usages.
     */
  readonly totalUsage: LanguageModelUsage;
  /**
  Warnings from the model provider (e.g. unsupported settings)
     */
  readonly warnings: CallWarning[] | undefined;
  /**
  Additional request information.
     */
  readonly request: LanguageModelRequestMetadata;
  /**
  Additional response information.
     */
  readonly response: LanguageModelResponseMetadata & {
    /**
    The response messages that were generated during the call. It consists of an assistant message,
    potentially containing tool calls.
    
    When there are tool results, there is an additional tool message with the tool results that are available.
    If there are tools that do not have execute functions, they are not included in the tool results and
    need to be added separately.
           */
    messages: Array<ResponseMessage>;
    /**
    Response body (available only for providers that use HTTP requests).
         */
    body?: unknown;
  };
  /**
  Additional provider-specific metadata. They are passed through
  from the provider to the AI SDK and enable provider-specific
  results that can be fully encapsulated in the provider.
     */
  readonly providerMetadata: ProviderMetadata | undefined;
  /**
  Details for all steps.
  You can use this to get information about intermediate steps,
  such as the tool calls or the response headers.
     */
  readonly steps: Array<StepResult<TOOLS>>;
  /**
  The generated structured output. It uses the `experimental_output` specification.
     */
  readonly experimental_output: OUTPUT;
}

export function generateText<
  TOOLS extends ToolSet,
  OUTPUT = never,
  OUTPUT_PARTIAL = never,
>({
  model: modelArg,
  tools,
  toolChoice,
  system,
  prompt,
  messages,
  maxRetries: maxRetriesArg,
  abortSignal,
  headers,
  stopWhen,
  experimental_output: output,
  experimental_telemetry: telemetry,
  providerOptions,
  experimental_activeTools,
  activeTools,
  experimental_prepareStep,
  prepareStep,
  experimental_repairToolCall: repairToolCall,
  experimental_context,
  _internal: { generateId, currentDate },
  onStepFinish,
  ...settings
}: CallSettings &
  Prompt & {
    /**
The language model to use.
     */
    model: LanguageModel;
    /**
The tools that the model can call. The model needs to support calling tools.
*/
    tools?: TOOLS;
    /**
The tool choice strategy. Default: 'auto'.
     */
    toolChoice?: ToolChoice<NoInfer<TOOLS>>;
    /**
Condition for stopping the generation when there are tool results in the last step.
When the condition is an array, any of the conditions can be met to stop the generation.

@default stepCountIs(1)
     */
    stopWhen?:
      | StopCondition<NoInfer<TOOLS>>
      | Array<StopCondition<NoInfer<TOOLS>>>;
    /**
Optional telemetry configuration (experimental).
     */
    experimental_telemetry?: TelemetrySettings;
    /**
Additional provider-specific options. They are passed through
to the provider from the AI SDK and enable provider-specific
functionality that can be fully encapsulated in the provider.
 */
    providerOptions?: ProviderOptions;
    /**
     * @deprecated Use `activeTools` instead.
     */
    experimental_activeTools?: Array<keyof NoInfer<TOOLS>>;
    /**
Limits the tools that are available for the model to call without
changing the tool call and result types in the result.
     */
    activeTools?: Array<keyof NoInfer<TOOLS>>;
    /**
Optional specification for parsing structured outputs from the LLM response.
     */
    experimental_output?: Output<OUTPUT, OUTPUT_PARTIAL>;
    /**
     * @deprecated Use `prepareStep` instead.
     */
    experimental_prepareStep?: PrepareStepFunction<NoInfer<TOOLS>>;
    /**
Optional function that you can use to provide different settings for a step.
    */
    prepareStep?: PrepareStepFunction<NoInfer<TOOLS>>;
    /**
A function that attempts to repair a tool call that failed to parse.
     */
    experimental_repairToolCall?: ToolCallRepairFunction<NoInfer<TOOLS>>;
    /**
    Callback that is called when each step (LLM call) is finished, including intermediate steps.
    */
    onStepFinish?: GenerateTextOnStepFinishCallback<NoInfer<TOOLS>>;
    /**
     * Context that is passed into tool execution.
     *
     * Experimental (can break in patch releases).
     *
     * @default undefined
     */
    experimental_context?: unknown;
    /**
     * Internal. For test use only. May change without notice.
     */
    _internal?: {
      generateId?: IdGenerator;
      currentDate?: () => Date;
    };
  }): Promise<GenerateTextResult<TOOLS, OUTPUT>>;
